drop table book;

create table book (
    book_id number generated by default as identity primary key,
    title varchar2(200) not null,
    author varchar2(100) not null,
    genre varchar2(50),
    price number(6,2),
    published_on date,
    available char(1) default 'Y' check (available in ('Y', 'N'))
);

insert into book (title, author, genre, price, published_on) values
('The Great Gatsby', 'F. Scott Fitzgerald', 'Classic', 10.99, to_date('1925-04-10', 'yyyy-mm-dd'));

insert into book (title, author, genre, price, published_on, available) values
('1984', 'George Orwell', 'Dystopian', 8.50, to_date('1949-06-08', 'yyyy-mm-dd'), 'Y');

insert into book (title, author, genre, price, published_on, available) values
('Clean Code', 'Robert C. Martin', 'Programming', 34.95, to_date('2008-08-01', 'yyyy-mm-dd'), 'Y');

insert into book (title, author, genre, price, published_on, available) values
('The Catcher in the Rye', 'J.D. Salinger', 'Classic', 9.99, to_date('1951-07-16', 'yyyy-mm-dd'), 'N');

insert into book (title, author, genre, price, published_on, available) values
('Atomic Habits', 'James Clear', 'Self-help', 18.00, to_date('2018-10-16', 'yyyy-mm-dd'), 'Y');

select * from book;

set SERVEROUTPUT on;

-- type for a specific row
declare
v_title book.title%type;
v_author book.author%type;
v_genre book.genre%type;
begin
select title, author, genre into v_title, v_author, v_genre
from book
where book_id = 1;
dbms_output.put_line('book name is ' || v_title || ' author is ' || v_author || ' genre is ' || v_genre);
end;

--rowtype for a all rows
declare
v_book book%rowtype;
begin
select * into v_book
from book
where book_id = 1;
dbms_output.put_line('book name is ' || v_book.title || ' author is ' || v_book.author || ' genre is ' || v_book.genre);
end;
