create database bank;

use bank;

CREATE TABLE CUSTOMER (
CUSTOMER_NO CHAR (5) PRIMARY KEY ,
CUSTOMER_NAME VARCHAR (20) NOT NULL ,
CUSTOMER_CITY VARCHAR (10)
) ;
CREATE TABLE ACCOUNT (
ACCOUNT_NO CHAR (5) PRIMARY KEY ,
BALANCE DECIMAL (12 ,2) NOT NULL
) ;
CREATE TABLE DEPOSITOR (
CUSTOMER_NO CHAR (5) ,
ACCOUNT_NO CHAR (5) ,
PRIMARY KEY ( CUSTOMER_NO , ACCOUNT_NO )
) ;

INSERT INTO CUSTOMER ( CUSTOMER_NO , CUSTOMER_NAME , CUSTOMER_CITY ) VALUES ('C-101', 'John Doe', 'DHK');
INSERT INTO CUSTOMER ( CUSTOMER_NO , CUSTOMER_NAME , CUSTOMER_CITY ) VALUES('C-102', 'Jane Smith', 'KHL');
INSERT INTO CUSTOMER ( CUSTOMER_NO , CUSTOMER_NAME , CUSTOMER_CITY ) VALUES('C-103', 'Alice Brown', 'CTG');
INSERT INTO CUSTOMER ( CUSTOMER_NO , CUSTOMER_NAME , CUSTOMER_CITY ) VALUES ('C-104', 'Bob Johnson', 'DHK');

INSERT INTO ACCOUNT ( ACCOUNT_NO , BALANCE ) VALUES('A-101', 5000.00);
INSERT INTO ACCOUNT ( ACCOUNT_NO , BALANCE ) VALUES ('A-102', 15000.00);
INSERT INTO ACCOUNT ( ACCOUNT_NO , BALANCE ) VALUES ('A-103', 25000.00);
INSERT INTO ACCOUNT ( ACCOUNT_NO , BALANCE ) VALUES ('A-104', 8000.00);

INSERT INTO DEPOSITOR ( CUSTOMER_NO , ACCOUNT_NO ) VALUES ('C-101', 'A-101');
INSERT INTO DEPOSITOR ( CUSTOMER_NO , ACCOUNT_NO ) VALUES ('C-102', 'A-102');
INSERT INTO DEPOSITOR ( CUSTOMER_NO , ACCOUNT_NO ) VALUES ('C-103', 'A-103');
INSERT INTO DEPOSITOR ( CUSTOMER_NO , ACCOUNT_NO ) VALUES ('C-104', 'A-104');

ALTER TABLE CUSTOMER
ADD DATE_OF_BIRTH DATE;

ALTER TABLE DEPOSITOR
RENAME TO DEPOSITOR_INFO;

ALTER TABLE DEPOSITOR_INFO
CHANGE COLUMN CUSTOMER_NO C_NO CHAR(5),
CHANGE COLUMN ACCOUNT_NO A_NO CHAR(5);

ALTER TABLE DEPOSITOR_INFO
ADD CONSTRAINT fk_customer_no FOREIGN KEY (C_NO) REFERENCES CUSTOMER(CUSTOMER_NO);
ALTER TABLE DEPOSITOR_INFO
ADD CONSTRAINT fk_account_no FOREIGN KEY (A_NO) REFERENCES ACCOUNT(ACCOUNT_NO);

SELECT * FROM CUSTOMER;

SELECT CUSTOMER.CUSTOMER_NAME, ACCOUNT.BALANCE
FROM CUSTOMER
INNER JOIN DEPOSITOR_INFO
ON
CUSTOMER.CUSTOMER_NO = DEPOSITOR_INFO.C_NO
INNER JOIN ACCOUNT
ON
DEPOSITOR_INFO.A_NO = ACCOUNT.ACCOUNT_NO;

SELECT AVG(BALANCE)
FROM ACCOUNT;

SELECT CUSTOMER_NAME, ACCOUNT_NO
FROM CUSTOMER
NATURAL JOIN DEPOSITOR_INFO;

UPDATE CUSTOMER
SET CUSTOMER_CITY = 'KLN'
WHERE CUSTOMER_NO = 'C-102';

DELETE FROM ACCOUNT
WHERE ACCOUNT_NO = 'A-104';

DELETE FROM CUSTOMER
WHERE CUSTOMER_NO NOT IN (
    SELECT C_NO FROM DEPOSITOR_INFO
);

